---
- name: Create ONTAP SVM
  hosts: localhost
  gather_facts: false

  collections:
    - netapp.ontap

  vars:
    protocol_list: "{{ allowed_protocols.split(',') | map('trim') | list }}"

  tasks:
    - name: Show input values
      ansible.builtin.debug:
        msg:
          - "Cluster: {{ hostname }}"
          - "SVM Name: {{ svm_name }}"
          - "Root Aggregate: {{ root_volume_aggregate }}"
          - "Security Style: {{ security_style }}"
          - "Allowed Protocols: {{ protocol_list }}"
          - "IPspace: {{ ipspace }}"

    - name: Create ONTAP SVM / Vserver
      netapp.ontap.na_ontap_svm:
        state: present
        name: "{{ svm_name }}"
        root_volume: "{{ svm_name }}_root"
        root_volume_aggregate: "{{ root_volume_aggregate }}"
        root_volume_security_style: "{{ security_style }}"
        allowed_protocols: "{{ protocol_list }}"
        ipspace: "{{ ipspace }}"
        language: C.UTF-8
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
      register: svm_result

    - name: Show SVM creation result
      ansible.builtin.debug:
        var: svm_result
