---
- hosts: localhost
  name: Create ONTAP SVM
  gather_facts: false

  collections:
    - netapp.ontap

  tasks:

    - name: Create ONTAP SVM / Vserver
      na_ontap_svm:
        state: present
        name: "{{ svm_name }}"
        root_volume: "{{ svm_name }}_root"
        root_volume_aggregate: "{{ root_volume_aggregate }}"
        root_volume_security_style: "{{ security_style }}"
        allowed_protocols: "{{ allowed_protocols }}"
        ipspace: "{{ ipspace }}"
        language: C.UTF-8

        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false

      register: svm_result

    - name: Display SVM creation status
      debug:
        msg: |
          SVM creation completed.

          Cluster     : {{ hostname }}
          SVM Name    : {{ svm_name }}
          Root Volume : {{ svm_name }}_root
          Aggregate   : {{ root_volume_aggregate }}
          Security    : {{ security_style }}
          Protocols   : {{ allowed_protocols }}
          IPspace     : {{ ipspace }}
