---
- name: NetApp Health Check Report
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Start HC Report
      debug:
        msg: "Generating Health Check Report for {{ hostname }}"

    - name: Create Report
      copy:
        dest: "/tmp/{{ report_name }}"
        content: |
          ===================================
          NetApp ONTAP Health Check Report
          ===================================

          Cluster : {{ hostname }}

          Include Nodes      : {{ include_nodes }}
          Include Aggregates : {{ include_aggrs }}
          Include Volumes    : {{ include_volumes }}
          Include LIFs       : {{ include_lifs }}
          Include SnapMirror : {{ include_snapmirror }}

          Report Generated Successfully.

    - name: Show Report Path
      debug:
        msg: "Report saved to /tmp/{{ report_name }}"
